# build site:
#   image: node:6
#   stage: build
#   script:
#     - npm install --progress=false
#     - npm run build
#   artifacts:
#     paths:
#       - dist
#   only:
#   - master

cache:
  paths: 
    - node_modules/ # Node modules and dependencies
  
pages:
  image: node:6
  
  stage: deploy
  script:
  - npm install --progress=false
  - npm run build
  - mkdir .public
  - cp -r ./dist ./public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
  